name: Get Russian blacklist of domains 

on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download file
      run: wget -O rublacklist https://antifilter.download/list/domains.lst

    - name: Files compare
      run: |
          ls -l data/rublacklist | awk '{print $5}'
          sha256sum data/rublacklist | awk '{print $1}'
          ls -l rublacklist | awk '{print $5}'
          sha256sum rublacklist | awk '{print $1}'

        
    - name: Commit changes
      run: |
        mv rublacklist data
        git init
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@noreply.github.com"
        git add .
        git commit -m "Updated on $(date)"
        # git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push origin master
