name: Test PR
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/go.mod

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        shell: bash

      - name: Build geosite.dat file
        run: |
          cd code || exit 1
          go run ./ --outputdir=../ --exportlists=rublacklist,youtube
          cd ../ && rm -rf code
          mv geosite.dat TEST-${{ github.run_number }}-geosite.dat

      - name: Upload TEST-${{ github.run_number }}-geosite.dat
        uses: actions/upload-artifact@v4
        with:
          name: TEST-${{ github.run_number }}-geosite.dat
          path: TEST-${{ github.run_number }}-geosite.dat
